### PR TITLE
Support separate Video-on-Demand VLAN

### PR DESCRIPTION
**Pull request by apedroheringer**
@jotala made a script to run on boot that connects to 602 vlan. I put this script on the end of udm-iptv, and the variables are set when vivogvt profile is chosen....

### CODE REVIEW

**Comment by fabianishere** [comment]
Thank you for your contribution! 

I will be waiting a bit to see whether others also interested in this functionality before integrating it (from a maintainability perspective).

**Comment by jotala** [comment]
@fabianishere 
Can you consider add the option to add adicional VLAN manually? 
This would be so helpful for those needing VOIP, VOD.
Thank you for your amazing work.

**Comment by fabianishere** [comment]
@jotala It might be easier to create a boot script to create the VOIP VLAN. It can be as easy as:

```bash
ip link add link eth8 name voip type vlan id VLAN_ID
```

**Comment by GBember01** [comment]
@apedroheringer sorry to necro this pull request, do you still use your Vivo IPTV with this? For the love of my life I can't set this up on RouterOS and this Unifi setup is the only clue I have its actually possible.

**Pull request closed without merging**
